// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HealthyCareAssistant.Contact.Repo.Entity;

public partial class ChatbotService
{
    public int ServiceId { get; set; }

    public string ServiceType { get; set; }

    public string ResponseTemplate { get; set; }

    public string Description { get; set; }

    public virtual ICollection<MessageHistory> MessageHistories { get; set; } = new List<MessageHistory>();
}