// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HealthyCareAssistant.Contact.Repo.Entity;

public partial class MedicineCabinetDrug
{
    public int CabinetDrugId { get; set; }

    public int? CabinetId { get; set; }

    public string DrugId { get; set; }

    public string Note { get; set; }

    public virtual MedicineCabinet Cabinet { get; set; }

    public virtual Drug Drug { get; set; }
}