// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HealthyCareAssistant.Contact.Repo.Entity;

public partial class MedicineCabinet
{
    public int CabinetId { get; set; }

    public int? UserId { get; set; }

    public string CabinetName { get; set; }

    public string Description { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<MedicineCabinetDrug> MedicineCabinetDrugs { get; set; } = new List<MedicineCabinetDrug>();

    public virtual User User { get; set; }
}