// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HealthyCareAssistant.Contact.Repo.Entity;

public partial class MessageHistory
{
    public int MessageId { get; set; }

    public int? UserId { get; set; }

    public int? ChatbotServiceId { get; set; }

    public string MessageType { get; set; }

    public string Content { get; set; }

    public DateTime? SentAt { get; set; }

    public virtual ChatbotService ChatbotService { get; set; }

    public virtual User User { get; set; }
}