// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HealthyCareAssistant.Contact.Repo.Entity;

public partial class Product
{
    public int ProductId { get; set; }

    public int? CategoryId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string Usage { get; set; }

    public string Dosage { get; set; }

    public string Image { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Category Category { get; set; }

    public virtual ICollection<Packaging> Packagings { get; set; } = new List<Packaging>();

    public virtual ICollection<ReminderProduct> ReminderProducts { get; set; } = new List<ReminderProduct>();
}