// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HealthyCareAssistant.Contact.Repo.Entity;

public partial class Reminder
{
    public int ReminderId { get; set; }

    public int? UserId { get; set; }

    public string Note { get; set; }

    public TimeOnly? ReminderTime { get; set; }

    public string RepeatDays { get; set; }

    public bool? IsOneTime { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<ReminderDrug> ReminderDrugs { get; set; } = new List<ReminderDrug>();

    public virtual User User { get; set; }
}