// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HealthyCareAssistant.Contact.Repo.Entity;

public partial class ReminderDrug
{
    public int ReminderDrugId { get; set; }

    public int? ReminderId { get; set; }

    public string DrugId { get; set; }

    public virtual Drug Drug { get; set; }

    public virtual Reminder Reminder { get; set; }
}