// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HealthyCareAssistant.Contact.Repo.Entity;

public partial class ReminderProduct
{
    public int ReminderProductId { get; set; }

    public int? ReminderId { get; set; }

    public int? ProductId { get; set; }

    public int? Quantity { get; set; }

    public string Note { get; set; }

    public virtual Product Product { get; set; }

    public virtual Reminder Reminder { get; set; }
}